TRUNCATE TABLE
  public.invoices,
  public.expenses,
  public.maintenance_request_comments,
  public.support_staff,
  public.property_terms,
  public.owner_billing,
  public.property_billing,
  public.phone_otp_challenges,
  public.data_deletion_requests,
  public.consent_records,
  public.audit_logs,
  public.login_activity,
  public.invite_codes,
  public.subscriptions,
  public.maintenance_requests,
  public.notices,
  public.payments,
  public.tenants,
  public.rooms,
  public.floors,
  public.hostels,
  public.owners
RESTART IDENTITY CASCADE;