"use client"
import * as React from "react"
import { X } from "lucide-react"
import { cn } from "../../lib/utils"
type DialogState = { open: boolean; setOpen: (open: boolean) => void }
const DialogContext = React.createContext<DialogState | null>(null)
const Dialog = ({ open: controlled, defaultOpen = false, onOpenChange, children }: { open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; children: React.ReactNode }) => { const [internal, setInternal] = React.useState(defaultOpen); const open = controlled ?? internal; const setOpen = (next: boolean) => { if (controlled === undefined) setInternal(next); onOpenChange?.(next) }; return <DialogContext.Provider value={{ open, setOpen }}>{children}</DialogContext.Provider> }
const child = (element: React.ReactElement, props: Record<string, unknown>) => React.cloneElement(element, { ...props, className: cn(props.className as string | undefined, (element.props as { className?: string }).className) })
const DialogTrigger = ({ asChild, children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { asChild?: boolean }) => { const state = React.useContext(DialogContext); const onClick = (event: React.MouseEvent<HTMLButtonElement>) => { props.onClick?.(event); state?.setOpen(true) }; return asChild ? child(children as React.ReactElement, { ...props, onClick }) : <button type="button" {...props} onClick={onClick}>{children}</button> }
const DialogClose = ({ asChild, children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { asChild?: boolean }) => { const state = React.useContext(DialogContext); const onClick = (event: React.MouseEvent<HTMLButtonElement>) => { props.onClick?.(event); state?.setOpen(false) }; return asChild ? child(children as React.ReactElement, { ...props, onClick }) : <button type="button" {...props} onClick={onClick}>{children}</button> }
const DialogPortal = ({ children }: { children: React.ReactNode }) => <>{children}</>
const DialogOverlay = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => <div ref={ref} className={cn("fixed inset-0 z-50 bg-black/80", className)} {...props} />)
DialogOverlay.displayName = "DialogOverlay"
const DialogContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement> & { onInteractOutside?: (event: React.MouseEvent<HTMLDivElement>) => void }>(({ className, children, onInteractOutside, ...props }, ref) => { const state = React.useContext(DialogContext); if (!state?.open) return null; return <DialogPortal><DialogOverlay onClick={(event) => { onInteractOutside?.(event); state.setOpen(false) }} /><div ref={ref} role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()} className={cn("fixed left-1/2 top-1/2 z-50 grid max-h-[90vh] w-full max-w-lg -translate-x-1/2 -translate-y-1/2 gap-4 overflow-y-auto border bg-background p-6 shadow-lg sm:rounded-2xl", className)} {...props}>{children}<DialogClose className="absolute right-4 top-4 opacity-70 hover:opacity-100"><X className="h-4 w-4" /><span className="sr-only">Close</span></DialogClose></div></DialogPortal> })
DialogContent.displayName = "DialogContent"
const DialogHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn("flex flex-col space-y-1.5", className)} {...props} />
const DialogFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2", className)} {...props} />
const DialogTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(({ className, ...props }, ref) => <h2 ref={ref} className={cn("text-lg font-semibold leading-none", className)} {...props} />)
const DialogDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement> & { asChild?: boolean }>(({ className, asChild, children, ...props }, ref) => asChild ? <>{children}</> : <p ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props}>{children}</p>)
DialogTitle.displayName = "DialogTitle"
DialogDescription.displayName = "DialogDescription"
export { Dialog, DialogPortal, DialogOverlay, DialogClose, DialogTrigger, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription }